POST http://localhost:8080/login

{
    "username": "Admin",
    "email": "phucnguyentrangia@gmail.com"
}

###
POST http://localhost:8080/localhost:8080/register 
{
    "username": "phuc",
    "email": "phuc@gmail.com"
}
